<?php
return [
    "Vice President - Business Unit Head",
    "Director",
    "N/A",
    "Manager - Account & Finance",
    "CEO",
    "Senior Vice President (SVP) - Management Committee",
    "Manager - Business Development",
    "Assistant Executive - Customer Support",
    "Senior Manager - Business Development",
    "Senior Manager - Customer Support",
    "3D Animator",
    "Sr. Executive Vice President - SEVP",
    "Assistant Vice President - Customer Support",
    "Sr.Manager",
    "Senior Executive - UI/UX Developer",
    "Sales Executive",
    "Sales Executive - Customer Support",
    "Intern - Graphic Designer",
    "IT Support",
    "Senior Executive - Customer Support",
    "Business Development Executive",
    "Senior Business Development Executive",
    "Assistant Manager - Customer Support",
    "Sweeper",
    "Cleaning boys",
    "Tea boys",
    "Business Development  - Executive"
];
